CREATE TYPE "public"."chase_status_type" AS ENUM('SHORT', 'LONG', 'AWAITING_SHORT', 'AWAITING_LONG', 'AWAITING_SIGNAL');--> statement-breakpoint
CREATE TYPE "public"."day_of_week_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');--> statement-breakpoint
CREATE TYPE "public"."job_execution_status" AS ENUM('PENDING', 'QUEUE', 'EXECUTING', 'COMPLETED', 'FAILED', 'REJECT', 'CANCELLED', 'SQUARED_OFF');--> statement-breakpoint
CREATE TYPE "public"."job_execution_strategy" AS ENUM('ATM_STRADDLE', 'ATM_STRANGLE', 'SUBSCRIBE_CHASE');--> statement-breakpoint
CREATE TABLE "accesstoken" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"access_token" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chase_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chase_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone NOT NULL,
	"tradingsymbol" text NOT NULL,
	"transaction_type" text NOT NULL,
	"average_price" numeric
);
--> statement-breakpoint
CREATE TABLE "chase_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"last_modified_at" timestamp with time zone DEFAULT now(),
	"current_status" "chase_status_type",
	"tradingsymbol" text,
	"instrument_token" integer,
	"stoploss" integer,
	"entry_point" integer,
	"is_signal_breaching_tolerance" boolean
);
--> statement-breakpoint
CREATE TABLE "ema" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"tradingsymbol" text NOT NULL,
	"ema" integer,
	"instrument_token" integer,
	"highest_high" integer,
	"lowest_low" integer,
	"last_close" integer
);
--> statement-breakpoint
CREATE TABLE "job_executions" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"status" "job_execution_status",
	"instrument" text,
	"strategy" "job_execution_strategy",
	"exit_strategy" text,
	"combined_exit_strategy" text,
	"expiry_type" text,
	"product_type" text,
	"volatility_type" text,
	"sl_order_type" text,
	"order_tag" text,
	"lots" smallint,
	"slm_percent" numeric,
	"sl_limit_price_percent" numeric,
	"max_profit_points" numeric,
	"max_loss_points" numeric,
	"current_points" numeric,
	"trailing_sl_percent" numeric,
	"trailing_max_profit_points" numeric,
	"trailing_max_loss_points" numeric,
	"trail_every_pct_change_value" numeric,
	"threshold_skew_percent" numeric,
	"max_skew_percent" numeric,
	"expire_if_unsuccessful_in_mins" smallint,
	"is_max_profit_enabled" boolean DEFAULT false,
	"is_max_loss_enabled" boolean DEFAULT false,
	"is_auto_square_off_enabled" boolean DEFAULT false,
	"take_trade_irrespective_skew" boolean DEFAULT false,
	"on_square_off_set_aborted" boolean DEFAULT false,
	"run_now" boolean DEFAULT false,
	"square_off_time" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"run_at" timestamp with time zone,
	"last_target_at" timestamp with time zone,
	"last_modified" timestamp with time zone,
	"auto_square_off_props" jsonb,
	"queue" jsonb,
	"auto_square_off_time" timestamp with time zone,
	"auto_square_off_delete_pending_orders" boolean DEFAULT false,
	"day_of_week" "day_of_week_enum",
	"trail_every_percentage_change_value" smallint,
	"plan_ref" text,
	"user_override" text,
	"live_trailing_sl" numeric,
	"last_trailing_sl_set_at" timestamp with time zone,
	"last_heartbeat_at" timestamp with time zone,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "trade_plans" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"strategy" "job_execution_strategy" NOT NULL,
	"instrument" text NOT NULL,
	"expiry_type" text NOT NULL,
	"product_type" text NOT NULL,
	"day_of_week" "day_of_week_enum",
	"exit_strategy" text,
	"combined_exit_strategy" text,
	"run_at" timestamp with time zone,
	"square_off_time" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"expire_if_unsuccessful_in_mins" integer,
	"lots" integer NOT NULL,
	"slm_percent" smallint,
	"sl_order_type" text,
	"sl_limit_price_percent" smallint,
	"max_profit_points" smallint,
	"is_max_profit_enabled" boolean DEFAULT false,
	"max_loss_points" smallint,
	"is_max_loss_enabled" boolean DEFAULT false,
	"threshold_skew_percent" smallint,
	"max_skew_percent" smallint,
	"take_trade_irrespective_skew" boolean DEFAULT false,
	"volatility_type" text,
	"trail_every_percentage_change_value" smallint,
	"trailing_sl_percent" smallint,
	"trailing_max_profit_points" smallint,
	"trailing_max_loss_points" smallint,
	"is_auto_square_off_enabled" boolean DEFAULT false,
	"auto_square_off_time" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"order_timestamp" timestamp,
	"exchange" text,
	"tradingsymbol" text,
	"instrument_token" integer,
	"transaction_type" text,
	"quantity" integer,
	"average_price" numeric,
	"tag" text,
	"order_id" text,
	"variety" text,
	"order_type" text,
	"product" text
);
--> statement-breakpoint
ALTER TABLE "job_executions" ADD CONSTRAINT "job_executions_plan_ref_trade_plans_id_fk" FOREIGN KEY ("plan_ref") REFERENCES "public"."trade_plans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_trade_plans_created_at" ON "trade_plans" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_trade_plans_instrument" ON "trade_plans" USING btree ("instrument");--> statement-breakpoint
CREATE INDEX "idx_trade_plans_strategy" ON "trade_plans" USING btree ("strategy");